### ISSUE TITLE
only works on first table of a page

### ISSUE THREAD

**Issue by runout-at** [oiv/sortablejs#10]
the first table on a page is sortable
on all following tables <sortable> ... </sortable> does not work
tested with firefox/iceweasel 38.3.0

**Comment by oiv** [comment]
Hmm.. Works for me. Firefox, chrome etc.

**Comment by FyiurAmron** [comment]
can't confirm it on Chrome 49, FF 43... even IE 8.0 has it OK. I'm voting to close this as WORKSFORME or MOREINFONEEDED.

@runout-at please paste the JS console/debugger output - there should be an error reported there, care to paste it here?

OTOH, there are some bugs in the code (see https://github.com/oiv/sortablejs/issues/21), that can result in this effect. YMMV.

**Comment by runout-at** [comment]
interesting. maybe the issue disappered...
can't reproduce it anymore
