### ISSUE TITLE
Not compatible with PHP 7.0

### ISSUE THREAD

**Issue by eilko** [oiv/sortablejs#14]
I updated my site to PHP 7.0 and some pages went blank. Error log shows: 

PHP Fatal error:  Uncaught Error: Call to undefined function split() in /var/www/vhosts/eilko.nl/httpdocs/lib/plugins/sortablejs/syntax.php:114\nStack trace:\n#0 /var/www/vhosts/eilko.nl/httpdocs/lib/plugins/sortablejs/syntax.php(51)

when I disable the sortablejs plugin the page shows again. Can you fix this error?

**Comment by oiv** [comment]
Hi

Thanks for the report. I commited a change for this. Hope it works now.

**Comment by eilko** [comment]
Thanks, it works

**Comment by FyiurAmron** [comment]
see https://github.com/oiv/sortablejs/pull/18 - possibly still not PHP 7 compatible.
